/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["LoginBody"];
                };
            };
            responses: {
                /** @description Login successful */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AuthResponse"];
                    };
                };
                /** @description Invalid credentials */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Logout successful */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get current user */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Current user */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: components["schemas"]["AuthUser"];
                        };
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/submissions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List submissions */
        get: {
            parameters: {
                query?: {
                    page?: number;
                    pageSize?: number;
                    status?: components["schemas"]["SubmissionStatus"];
                    type?: components["schemas"]["SubmissionType"];
                    tier?: components["schemas"]["SubmitterTier"];
                    search?: string;
                    sortBy?: "createdAt" | "score" | "flagCount";
                    sortOrder?: components["schemas"]["SortOrder"];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Paginated submission list */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: components["schemas"]["Submission"][];
                            pagination: components["schemas"]["Pagination"];
                        };
                    };
                };
            };
        };
        put?: never;
        /** Create submission */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["SubmissionCreateBody"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: components["schemas"]["Submission"];
                        };
                    };
                };
                /** @description Validation error */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/submissions/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["SubmissionId"];
            };
            cookie?: never;
        };
        /** Get submission by id */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["SubmissionId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Submission detail */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: components["schemas"]["Submission"];
                        };
                    };
                };
                /** @description Not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        /** Delete submission */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["SubmissionId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Deleted */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        /** Update submission */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["SubmissionId"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["SubmissionUpdateBody"];
                };
            };
            responses: {
                /** @description Updated */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: components["schemas"]["Submission"];
                        };
                    };
                };
                /** @description Not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Validation error */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        trace?: never;
    };
    "/submissions/batch-review": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Batch approve or reject submissions */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["BatchReviewBody"];
                };
            };
            responses: {
                /** @description Batch review result */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            updatedCount: number;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/submissions/batch-delete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Batch delete submissions */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["BatchDeleteBody"];
                };
            };
            responses: {
                /** @description Batch delete result */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            deletedCount: number;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/dashboard/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get dashboard statistics */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Dashboard stats */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: components["schemas"]["DashboardStats"];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @enum {string} */
        SubmissionStatus: "pending" | "approved" | "rejected" | "flagged";
        /** @enum {string} */
        SubmissionType: "article" | "image" | "video" | "link";
        /** @enum {string} */
        SubmitterTier: "free" | "pro" | "verified";
        /** @enum {string} */
        VideoResolution: "480p" | "720p" | "1080p" | "4k";
        /** @enum {string} */
        ReviewVerdict: "approved" | "rejected";
        /** @enum {string} */
        SortOrder: "asc" | "desc";
        Pagination: {
            page: number;
            pageSize: number;
            total: number;
            totalPages: number;
        };
        ErrorResponse: {
            error: {
                code: string;
                message: string;
            };
        };
        Submitter: {
            id: string;
            name: string;
            /** Format: email */
            email: string;
            tier: components["schemas"]["SubmitterTier"];
        };
        BaseContent: {
            /** Format: uri */
            url: string;
            /** Format: uri */
            thumbnailUrl: string | null;
        };
        ArticleContent: components["schemas"]["BaseContent"] & {
            /** @enum {string} */
            type: "article";
            wordCount: number;
            readingTime: number;
        } & {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "article";
        };
        VideoContent: components["schemas"]["BaseContent"] & {
            /** @enum {string} */
            type: "video";
            duration: number;
            resolution: components["schemas"]["VideoResolution"];
        } & {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "video";
        };
        ImageContent: components["schemas"]["BaseContent"] & {
            /** @enum {string} */
            type: "image";
            width: number;
            height: number;
        } & {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "image";
        };
        LinkContent: components["schemas"]["BaseContent"] & {
            /** @enum {string} */
            type: "link";
            domain: string;
            isBehindPaywall: boolean;
        } & {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "link";
        };
        Content: components["schemas"]["ArticleContent"] | components["schemas"]["VideoContent"] | components["schemas"]["ImageContent"] | components["schemas"]["LinkContent"];
        Review: {
            reviewerId: string;
            verdict: components["schemas"]["ReviewVerdict"];
            reason: string;
            /** Format: date-time */
            reviewedAt: string;
        };
        Submission: {
            id: string;
            title: string;
            type: components["schemas"]["SubmissionType"];
            status: components["schemas"]["SubmissionStatus"];
            submitter: components["schemas"]["Submitter"];
            content: components["schemas"]["Content"];
            tags: string[];
            review: components["schemas"]["Review"] | null;
            score: number;
            flagCount: number;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        SubmissionCreateBody: {
            title: string;
            type: components["schemas"]["SubmissionType"];
            tags: string[];
            content: components["schemas"]["Content"];
            /** Format: email */
            submitterEmail?: string;
        };
        SubmissionUpdateBody: {
            title?: string;
            tags?: string[];
            content?: components["schemas"]["Content"];
        };
        BatchReviewBody: {
            ids: string[];
            verdict: components["schemas"]["ReviewVerdict"];
            reason: string;
        };
        BatchDeleteBody: {
            ids: string[];
        };
        LoginBody: {
            /** Format: email */
            email: string;
            password: string;
        };
        AuthUser: {
            id: string;
            name: string;
            /** Format: email */
            email: string;
            /** @enum {string} */
            role: "admin" | "reviewer";
        };
        AuthResponse: {
            token: string;
            user: components["schemas"]["AuthUser"];
        };
        DashboardSummary: {
            totalSubmissions: number;
            pendingCount: number;
            approvedCount: number;
            rejectedCount: number;
            flaggedCount: number;
        };
        DashboardByType: {
            type: components["schemas"]["SubmissionType"];
            count: number;
            approvalRate: number;
        };
        RecentActivity: {
            submissionId: string;
            title: string;
            /** @enum {string} */
            action: "submitted" | "approved" | "rejected" | "flagged";
            actorName: string;
            /** Format: date-time */
            occurredAt: string;
        };
        TopSubmitter: {
            submitterId: string;
            name: string;
            tier: components["schemas"]["SubmitterTier"];
            submissionCount: number;
            approvalRate: number;
        };
        DashboardStats: {
            summary: components["schemas"]["DashboardSummary"];
            byType: components["schemas"]["DashboardByType"][];
            recentActivity: components["schemas"]["RecentActivity"][];
            topSubmitters: components["schemas"]["TopSubmitter"][];
        };
    };
    responses: never;
    parameters: {
        SubmissionId: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
